# Generated by Django 5.0.6 on 2024-06-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='/media/fallback.png', upload_to='media'),
        ),
    ]
