# Generated by Django 5.0.6 on 2024-06-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_category_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
